### PR TITLE
Add tool 7: Create basalt boxes

### PR DESCRIPTION
**Pull request by jvanegmond**
Playing around with UE4VoxelTerrain today and decided to add a tool to fill cubes in a similar way in which they can be removed. Implemented it fairly easily (I'm definitely a EU4 beginner) and had some fun making small mazes.

Not sure if you're accepting pull requests or want such a change. I've had some fun with it and thought to share.

This depends on another pull request, namely: https://github.com/bw2012/UnrealSandboxTerrain/pull/2

### CODE REVIEW

**Comment by jvanegmond** [comment]
image

Screenshot of how it looks in-game.

**Comment by bw2012** [comment]
It looks awesome. Thanks a lot for your contribution

**Comment by SvarogZ** [comment]
You have forgotten to implement the changes in the Terrain plugin here https://github.com/bw2012/UnrealSandboxTerrain/pull/2
Or maybe it's implemented with mistakes.
Downloaded wersionof project is not compiled without it.

**Comment by SvarogZ** [comment]
Oh, Sorry! I turned back my handmade version, next copied downloaded files again and rebuild the project again.
Successful.

**Pull request merged**
